### ISSUE TITLE
Does not seem to work as downloaded

### ISSUE THREAD

**Issue by JoshuaKimsey** [MattC137/NCAA-Football-Forecasts#1]
When trying to use the standard code in RStudio, it does not work correctly. The final tables are left empty and the console throws a number of errors seen below. How can this be fixed?

`Selecting by ELO

Error in family(object)$linkinv(pred) : 

  Argument eta must be a nonempty numeric vector

In addition: Warning messages:

1: Problem with mutate() input Result.

ℹ NAs introduced by coercion

ℹ Input Result is as.numeric(Result). 

2: In mask$eval_all_mutate(dots[[i]]) : NAs introduced by coercion`

**Comment by MattC137** [comment]
I suspect the problem is on line 118 where you need update the dates to select next weeks games. It's currently set to forecast yesterday's games. Otherwise your going to get a blank dataframe for NCAAF_This_Week. 

Warning aren't great but acceptable for a dataset this size. The source I scrapped the dataset from is not always extremely thorough in reporting some of the non-FBS games especially in earlier seasons (even though it's an very mainstream source). My guess is that's where some of the NAs are coming into play.

**Comment by MattC137** [comment]
FYI - I've pushed the date update so it should run through.

**Comment by MattC137** [comment]
I've cleaned up the script to avoid the warnings.

The warnings from the initial import were due to the fact that games that got canceled or postponed were labeled as such in the Game_ID variable. This caused them to get converted to NAs because read_csv() thought the column was a double.

The other issue I saw came about when converting the Results column. This was happening because future games were labeled 'TBD' in the results column. I moved a filter before the conversion to handle this and eliminate the warnings.

Thanks for identifying these warnings!
